import { Geist, Geist_Mono } from "next/font/google";
import "@mantine/core/styles.css";
import "./globals.css";
import { MantineProvider } from "@mantine/core"; // ✅ Import MantineProvider
import { Notifications } from "@mantine/notifications"; // ✅ Import Notifications

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Wrap everything inside MantineProvider */}
        <MantineProvider withGlobalStyles withNormalizeCSS>
          <Notifications /> 
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
